### ISSUE TITLE
Console application

### ISSUE THREAD

**Issue by plozanol** [mikededo/github-stats#13]
As a PO I want that the application will have a console look, allowing it to write and execute commands that will allow triggering differents actions in the application

Acceptance:
- define the list of commands that will be implemented
- document in the README.md file the console use and commands implemented

**Comment by mikededo** [comment]
From my point of view:

- Create issue to prototype the commands
- Create separate issues per command implementation

Note also that the implementation should not involve all the implementation of the command but rather the set up of it (i.e. be able to run the command and return mock data).
