### ISSUE TITLE
Document list of GitHub API requests needed

### ISSUE THREAD

**Issue by plozanol** [mikededo/github-stats#3]
As a PO I want to encapsulate all the logic needed to extract the data that will be consumed by the app.

Depends on: #4

Definition of Ready:
- From the flowchart, document the list of GitHub API requests needed.
- The documentation should be done via the [mdas-github-stats](https://go.postman.co/build/workspace/e6730e02-cf41-4b5d-b1b4-f064f3c61ef2/collection/13493919-2817efd3-1621-4c6f-8cb4-f12b8b723de7) Postman Workspace.

Acceptance:
- Model and encapsulate all the logic using a Proxy code pattern.
- Use the minimum request calls possible.
- Retrieve only the needed information from the API responses.
- Expose all the data to the application entities and persist the information.

**Comment by mikededo** [comment]
Is this ticket related only to the flow diagram for the api calls or also to their implementation?  
If it is the second option, wdyt about splitting?

**Comment by manerow** [comment]
I agree with splitting this issue. At least i can identify two separate issues from the definition of ready description. 

1. Design the GitHub API Request Flowchart.
2. Extract a list of the request calls needed from the Flowchart.

After extracting the request list, we should re-analyze and create the appropiate tasks for the implementation.

**Comment by manerow** [comment]
Since the issue for the first step is already created and assigned to @plozanol on #4, I propose to modify this issue removing from it the first part. The issue would be: "Extract the list of GitHub API Requests needed"

**Comment by manerow** [comment]
Uploaded the documentation on http://pksuns.pakland.io:6875/books/github-stats/page/documentacion-api-github.
