### ISSUE TITLE
Github Mocked API

### ISSUE THREAD

**Issue by plozanol** [mikededo/github-stats#5]
As a PO I want a mocked piece of software emulating the real GitHub API

Acceptance:
- will implement a Mock Server Using Postman that accepts and return the analyzed requests in the previous milestone

**Comment by mikededo** [comment]
Can assing myself to this, though I'm not familiar with it. 

Also, I consider this more a chore type as it is not a feature to add to the product.

**Comment by manerow** [comment]
The implementation of this issue should depend on #3. @mikededo can use the postman workspace responses for developig the Mock API.

**Comment by sdomingobasora** [comment]
I self-assigned this item after asking @mikededo

The Mock server will indeed be created in our shared Workspace and using the collections created as part of #3 and #4.
